# Generated by Django 4.1.3 on 2022-11-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tiger_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
